public class NewPage1 {

   

    public Decimal bprice1 { get; set; }

    public String aname1 { get; set; }

    public String bname1 { get; set; }

    public PageReference Cancel() {
        return null;
    }
    

    public PageReference setandnew() {
        return null;
    }


    public PageReference set() {
        return null;
    }


    public String Save { get; set; }

    public PageReference Save() {
        return null;
    }

}